services:
  # bonus
  redis:
    container_name: inception_redis
    restart: always
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
  #XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#


  # mandatory
  mariadb:
    container_name: inception_mariadb
    restart: always
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        - MARIADB_USER_ARG=${MARIADB_USER}
        - MARIADB_DATADIR_ARG=${MARIADB_DATADIR}
      secrets:
        - db_user_password
        - db_root_password
    volumes:
      - mariadb_vol:${MARIADB_DATADIR}
    networks:
      - mariadb_to_wordpress
    ports:
      - 3306
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATADIR=${MARIADB_DATADIR}

  wordpress:
    container_name: inception_wordpress
    restart: always
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      secrets:
        - wp_admin_name
        - wp_admin_email
        - wp_admin_password
        - wp_user_name
        - wp_user_email
        - wp_user_password
        - db_user_password
      args:
        - DOMAIN_NAME_ARG=${DOMAIN_NAME}
        - WP_TITLE_ARG=${WP_TITLE}
        - DB_USER_ARG=${MARIADB_USER}
        - DB_HOST_ARG=inception_mariadb
    networks:
      - mariadb_to_wordpress
      - wordpress_to_nginx
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    ports:
      - 9000
    extra_hosts:
      - ${DOMAIN_NAME}:127.0.0.1
    secrets:
      - wp_user_name
      - wp_user_email
      - wp_user_password
      - wp_admin_name
      - wp_admin_email
      - wp_admin_password
      - db_user_password
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - DB_USER=${MARIADB_USER}
      - DB_HOST=inception_mariadb

  nginx:
    container_name: inception_nginx
    restart: always
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
      secrets:
        - wp_cert
        - wp_cert_key
      args:
        - DOMAIN_NAME_ARG=${DOMAIN_NAME}
    ports:
      - 443:443
    networks:
      - nginx_to_host
      - wordpress_to_nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    extra_hosts:
      - ${DOMAIN_NAME}:127.0.0.1
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
networks:
# mariadb <-> wordpress
  mariadb_to_wordpress:
    driver: bridge

# wordpress <-> nginx
  wordpress_to_nginx:
    driver: bridge

# nginx <-> host
  nginx_to_host:
    driver: bridge


volumes:
# mariadb databases
  mariadb_vol:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${MARIADB_VOL}

# wordpress website data
  wordpress_vol:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${WORDPRESS_VOL}

# passwords and sensitive information
secrets:
# mariadb
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
# redis
  redis_password:
    file: ../secrets/redis_password.txt
# wordpress
  wp_admin_name:
    file: ../secrets/wp_admin_name.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_user_name:
    file: ../secrets/wp_user_name.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_user_email:
    file: ../secrets/wp_user_email.txt
# wordpress certificates
  wp_cert:
    file: ../secrets/wordpress.crt
  wp_cert_key:
    file: ../secrets/wordpress.key