services:
  mariadb:
    container_name: inception_mariadb
    restart: always
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
      - MYSQL_USER_ARG=${MYSQL_USER}
      - MYSQL_PASSWORD_ARG=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD_ARG=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATADIR_ARG=${MYSQL_DATADIR}
    volumes:
      - mariadb_vol:${MYSQL_DATADIR}
    networks:
      - mariadb_to_wordpress
    ports:
      - 3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATADIR=${MYSQL_DATADIR}

  wordpress:
    container_name: inception_wordpress
    restart: always
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
      - MYSQL_USER_ARG=${MYSQL_USER}
      - MYSQL_PASSWORD_ARG=${MYSQL_PASSWORD}
      - WP_ADMIN_ARG=${WP_ADMIN}
      - WP_ADMIN_EMAIL_ARG=${WP_ADMIN_EMAIL}
      - WP_ADMIN_PASSWORD_ARG=${WP_ADMIN_PASSWORD}
      - WP_TITLE_ARG=${WP_TITLE}
      - DOMAIN_NAME_ARG=${DOMAIN_NAME}
      - WP_USER_ARG=${WP_USER}
      - WP_EMAIL_ARG=${WP_EMAIL}
      - WP_PASSWORD_ARG=${WP_PASSWORD}
    networks:
      - mariadb_to_wordpress
      - wordpress_to_nginx
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    ports:
      - 9000
    extra_hosts:
      - ${DOMAIN_NAME}:127.0.0.1

  nginx:
    container_name: inception_nginx
    restart: always
    build:
      context:  ./requirements/nginx/
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - 443:443
    networks:
      - nginx_to_host
      - wordpress_to_nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    extra_hosts:
      - ${DOMAIN_NAME}:127.0.0.1

networks:
# mariadb <-> wordpress
  mariadb_to_wordpress:
    driver: bridge

# wordpress <-> nginx
  wordpress_to_nginx:
    driver: bridge

# nginx <-> host
  nginx_to_host:
    driver: bridge


volumes:
# mariadb databases
  mariadb_vol:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${MARIADB_VOL}

# wordpress website data
  wordpress_vol:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${WORDPRESS_VOL}